# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# Dockerfile for setting up Realsense driver
#  https://github.com/jetsonhacks/installRealSenseSDK
ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# 设置环境变量代理
ENV https_proxy=http://127.0.0.1:7890 \
    http_proxy=http://127.0.0.1:7890 \
    all_proxy=socks5://127.0.0.1:7890 \
    HTTPS_PROXY=http://127.0.0.1:7890 \
    HTTP_PROXY=http://127.0.0.1:7890 \
    ALL_PROXY=socks5://127.0.0.1:7890

# 为APT包管理器设置代理
RUN echo 'Acquire::http::Proxy "http://127.0.0.1:7890";' > /etc/apt/apt.conf.d/95proxies && \
    echo 'Acquire::https::Proxy "http://127.0.0.1:7890";' >> /etc/apt/apt.conf.d/95proxies && \
    echo 'Acquire::ftp::Proxy "http://127.0.0.1:7890";' >> /etc/apt/apt.conf.d/95proxies

# 为Git设置全局代理
RUN git config --global http.proxy http://127.0.0.1:7890 && \
    git config --global https.proxy http://127.0.0.1:7890

# 为Wget设置代理（写入配置文件）
RUN echo "use_proxy=yes" >> /etc/wgetrc && \
    echo "http_proxy=http://127.0.0.1:7890" >> /etc/wgetrc && \
    echo "https_proxy=http://127.0.0.1:7890" >> /etc/wgetrc && \
    echo "ftp_proxy=http://127.0.0.1:7890" >> /etc/wgetrc

# 为Curl设置代理（环境变量已覆盖，这里额外创建curl配置文件）
RUN echo "proxy = http://127.0.0.1:7890" > /root/.curlrc && \
    echo "socks5 = 127.0.0.1:7890" >> /root/.curlrc

ARG LIBREALSENSE_SOURCE_VERSION=v2.55.1
ARG REALSENSE_ROS_GIT_URL=https://github.com/NVIDIA-ISAAC-ROS/realsense-ros.git
ARG REALSENSE_ROS_VERSION=release/4.51.1-isaac

COPY scripts/build-librealsense.sh /opt/realsense/build-librealsense.sh
COPY scripts/install-realsense-dependencies.sh /opt/realsense/install-realsense-dependencies.sh

RUN chmod +x /opt/realsense/install-realsense-dependencies.sh && \
    /opt/realsense/install-realsense-dependencies.sh; \
    chmod +x /opt/realsense/build-librealsense.sh && /opt/realsense/build-librealsense.sh -v ${LIBREALSENSE_SOURCE_VERSION};

# Copy hotplug script for udev rules/hotplug for RealSense
RUN mkdir -p /opt/realsense/
COPY scripts/hotplug-realsense.sh /opt/realsense/hotplug-realsense.sh
COPY udev_rules/99-realsense-libusb-custom.rules /etc/udev/rules.d/99-realsense-libusb-custom.rules

# Install realsense-ros ROS 2 package
RUN --mount=type=cache,target=/var/cache/apt \
    mkdir -p ${ROS_ROOT}/src && cd ${ROS_ROOT}/src \
    && git clone ${REALSENSE_ROS_GIT_URL} -b ${REALSENSE_ROS_VERSION} \
    && cd realsense-ros && source ${ROS_ROOT}/setup.bash \
    && cd realsense2_camera_msgs && bloom-generate rosdebian && fakeroot debian/rules binary \
    && cd ../ && apt-get install -y ./*.deb && rm ./*.deb \
    && cd realsense2_description && bloom-generate rosdebian && fakeroot debian/rules binary \
    && cd ../ && apt-get install -y ./*.deb && rm ./*.deb \
    && cd realsense2_camera && bloom-generate rosdebian \
    && sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' debian/rules \
    && sed -i 's/ros-humble-librealsense2, //g' debian/control \
    && fakeroot debian/rules binary \
    && cd ../ && apt-get install -y ./*.deb && rm ./*.deb \
    && cd ../ && rm -Rf realsense-ros
